
CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE;


USE ALX_BOOK_STORE;

CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(215) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    CONSTRAINT FK_BOOKS_AUTHORS
        FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHORS (AUTHOR_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADDRESS TEXT
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    CONSTRAINT FK_ORDERDETAILS_ORDERS
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDERDETAILS_BOOKS
        FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (BOOK_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;
