-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS alx_book_store;

-- USE DATABASE
USE alx_book_store;

-- AUTHORS TABLE
CREATE TABLE IF NOT EXISTS Authors (
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(215) NOT NULL
) ENGINE=INNODB;

-- BOOKS TABLE
CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    CONSTRAINT FK_BOOKS_AUTHORS
        FOREIGN KEY (AUTHOR_ID)
        REFERENCES Authors (author_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;

-- CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADDRESS TEXT
) ENGINE=INNODB;

-- ORDERS TABLE
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDER DETAILS TABLE
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    CONSTRAINT FK_ORDERDETAILS_ORDERS
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDERDETAILS_BOOKS
        FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (BOOK_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB;
